commit

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -1,17 +1,43 @@
-name: BuildAndPackage
+# This workflow will build a golang project
+# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go
+
+name: Go build
 
 env:
-  ProJectName: "ltc_scrypt_go"
+  ProductName: ltc_scrypt_go
 
 on:
-  workflow_dispatch:
   push:
     tags:
-      - "v*"
+      - 'v*'
 
 jobs:
-  release:
+  Testing:
+    strategy:
+      matrix:
+        os: [macos-latest]
+        arch: [amd64, arm64]
+        exclude:
+          - os: windows-latest
+            arch: arm64
+    runs-on: ${{ matrix.os }}
+
+    steps:
+      - name: CheckOut
+        uses: actions/checkout@v4
+
+      - name: Set up Go
+        uses: actions/setup-go@v5
+        with:
+          go-version: '>=1.18.0'
+
+      - name: do testing
+        run: |
+          go test -v ./...  
+
+  Release:
     runs-on: ubuntu-latest
+    needs: Testing
     outputs:
       UPLOAD_URL: ${{ steps.stepCreateRelease.outputs.upload_url }}
     steps:
@@ -20,7 +46,7 @@ jobs:
 
       - name: Get latest tag
         run: |
-          echo "LATEST_TAG=$(git tag | grep -v '^latest$' | sort -V | tail -n1)" >> $GITHUB_ENV
+          echo "LATEST_TAG=$(git tag | grep -v '^latest$' | sort -V | tail -n1)" >> ${GITHUB_ENV}
 
       - name: Bump version and push tag
         id: tag-version
@@ -38,43 +64,9 @@ jobs:
           tag: ${{ env.LATEST_TAG }}
           name: ${{ env.LATEST_TAG }}
 
-  buildOnMacOS:
-    runs-on: macos-latest
-    needs: release
-    steps:
-      - name: CheckOut
-        uses: actions/checkout@v4
-
-      - name: install dependencies
-        run: |
-          brew install tree zip unzip openssl FiloSottile/musl-cross/musl-cross mingw-w64 mingw-w64-openssl
-
-      - name: Set up JDK 1.8
-        uses: actions/setup-java@v4
-        with:
-          distribution: 'temurin'
-          java-version: '21'
-
-      - name: Set up Android NDK
-        uses: nttld/setup-ndk@v1
-        id: setup-ndk
-        with:
-          ndk-version: r26d
-
-      - name: Build static library
-        run: |
-          chmod a+x ./build.sh
-          ./build.sh all
-
-      - name: Upload binaries to release
-        id: upload_file_to_release
-        uses: george012/upload_github_release_assets_action@latest
-        with:
-          path: ./build/*.zip
-
   RemoveOldRelease:
     runs-on: ubuntu-latest
-    needs: [buildOnMacOS]
+    needs: Release
     steps:
       - name: install github-cli
         run: |
@@ -91,7 +83,39 @@ jobs:
       - name: Set APP_VERSION env
         run: |
           APP_VERSION=$(echo ${GITHUB_REF} | rev | cut -d'/' -f 1 | rev ) \
-          && echo APP_OLD_VERSION=${APP_VERSION%.*}.$((${APP_VERSION##*.}-2)) >> ${GITHUB_ENV}
+
+          function get_pre_del_tag {
+              local v_str=$1
+              baseStr=$(echo $v_str | cut -d'.' -f1)
+              base=${baseStr//v/}
+              major=$(echo $v_str | cut -d'.' -f2)
+              minor=$(echo $v_str | cut -d'.' -f3)
+
+              if ((minor>0)); then
+                  minor=$((minor-1))
+              else
+                  minor=999
+                  if ((major>0)); then
+                      major=$((major-1))
+                  else
+                      major=999
+                      if ((base>0)); then
+                          base=$((base-1))
+                      else
+                          echo "Error: Version cannot be decremented."
+                          exit 1
+                      fi
+                  fi
+              fi
+
+              pre_v_no="v${base}.${major}.${minor}"
+              echo $pre_v_no
+          }
+
+          APP_OLD_VERSION=$(get_pre_del_tag $(get_pre_del_tag $APP_VERSION))
+
+          echo "Old version to remove: ${APP_OLD_VERSION}"
+          echo APP_OLD_VERSION=${APP_OLD_VERSION} >> ${GITHUB_ENV}
 
       - name: Remove Old Release
         run: |
